spring.application.name=cubamant
# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cubamant_db
spring.datasource.username=postgres
spring.datasource.password=zeky1984
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
#in production, consider using 'none' or 'validate' to prevent unintended schema changes
spring.jpa.hibernate.ddl-auto= create-drop 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect