-- USERS
CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    first_name varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    user_type varchar(31) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

-- AUTHORITY
CREATE TABLE authority (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    role varchar(255) NOT NULL,
    CONSTRAINT authority_role_check
        CHECK (role IN ('USER','SUPERUSER','ADMIN')),
    CONSTRAINT fk_authority_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

-- CUSTOMERS
CREATE TABLE customers (
    id bigint PRIMARY KEY,
    newsletter_subscribed boolean NOT NULL,
    created_at_customer timestamp(6) with time zone NOT NULL,
    company_name varchar(255),
    shipping_address varchar(255),
    CONSTRAINT fk_customers_user
        FOREIGN KEY (id) REFERENCES users(id)
);

-- WORKERS
CREATE TABLE workers (
    id bigint PRIMARY KEY,
    hourly_rate numeric(38,2),
    is_supervisor boolean NOT NULL,
    job_title smallint,
    created_at_worker timestamp(6) with time zone NOT NULL,
    CONSTRAINT workers_job_title_check
        CHECK (job_title BETWEEN 0 AND 4),
    CONSTRAINT fk_workers_user
        FOREIGN KEY (id) REFERENCES users(id)
);

-- PROJECT
CREATE TABLE project (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL,
    start_date date,
    end_date date,
    scheduled_hours integer,
    labor_cost numeric(38,2),
    material_cost numeric(38,2),
    total_cost numeric(38,2) NOT NULL,
    payment_status varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    CONSTRAINT project_payment_status_check
        CHECK (payment_status IN ('UNPAID','PARTIAL','PAID')),
    CONSTRAINT project_status_check
        CHECK (status IN ('PLANNED','IN_PROGRESS','COMPLETED')),
    CONSTRAINT fk_project_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- PROJECT_WORKERS (join table)
CREATE TABLE project_workers (
    project_id bigint NOT NULL,
    worker_id bigint NOT NULL,
    CONSTRAINT fk_project_workers_project
        FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_project_workers_worker
        FOREIGN KEY (worker_id) REFERENCES workers(id)
);

-- REVIEW
CREATE TABLE review (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating integer NOT NULL,
    comment varchar(1000),
    visibility varchar(255),
    created_at timestamp(6) NOT NULL,
    customer_id bigint NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT review_rating_check
        CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT review_visibility_check
        CHECK (visibility IN ('PUBLIC','PRIVATE')),
    CONSTRAINT fk_review_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_review_project
        FOREIGN KEY (project_id) REFERENCES project(id)
);

-- REVIEW_IMAGES
CREATE TABLE review_images (
    review_id bigint NOT NULL,
    image_url varchar(255),
    CONSTRAINT fk_review_images_review
        FOREIGN KEY (review_id) REFERENCES review(id)
);