-- USERS
create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password varchar(255) not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    user_type varchar(31),
    is_active boolean not null default true,
    created_at timestamp(6) with time zone not null default now()
);

-- AUTHORITY
create table authority (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    role varchar(255) not null,
    constraint authority_role_check check (role in ('ROLE_USER','ROLE_SUPERUSER','ROLE_ADMIN')),
    constraint fk_authority_user foreign key (user_id) references users(id),
    constraint unique_user_role unique(user_id, role)
);

-- CUSTOMERS
create table customers (
    id bigint primary key,
    newsletter_subscribed boolean not null default false,
    created_at timestamp(6) with time zone not null default now(),
    company_name varchar(255),
    shipping_address varchar(255),
    constraint fk_customers_user foreign key (id) references users(id)
);

-- WORKERS
create table workers (
    id bigint primary key,
    hourly_rate numeric(38,2),
    is_supervisor boolean not null default false,
    job_title varchar(50) not null,
    created_at timestamp(6) with time zone not null default now(),
    constraint workers_job_title_check
check (job_title in ('TECHNICIAN','FOREMAN','ENGINEER','ARCHITECT','ADMINISTRATOR','LABORER')),
    constraint fk_workers_user foreign key (id) references users(id)
);

-- PROJECT
create table project (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    start_date date,
    end_date date,
    scheduled_hours integer,
    labor_cost numeric(38,2),
    material_cost numeric(38,2),
    total_cost numeric(38,2) not null,
    payment_status varchar(255) not null default 'UNPAID',
    status varchar(255) not null default 'PLANNED',
    constraint project_payment_status_check check (payment_status in ('UNPAID','PARTIAL','PAID')),
    constraint project_status_check check (status in ('PLANNED','IN_PROGRESS','COMPLETED')),
    constraint fk_project_customer foreign key (customer_id) references customers(id)
);

-- PROJECT_WORKERS (join table)
create table project_workers (
    project_id bigint not null,
    worker_id bigint not null,
    constraint pk_project_workers primary key(project_id, worker_id),
    constraint fk_project_workers_project foreign key (project_id) references project(id),
    constraint fk_project_workers_worker foreign key (worker_id) references workers(id)
);

-- REVIEW
create table review (
    id bigint generated by default as identity primary key,
    rating integer not null,
    comment varchar(1000),
    visibility varchar(255) not null default 'PUBLIC',
    created_at timestamp(6) with time zone not null default now(),
    customer_id bigint not null,
    project_id bigint not null,
    constraint review_rating_check check (rating between 1 and 5),
    constraint review_visibility_check check (visibility in ('PUBLIC','PRIVATE')),
    constraint fk_review_customer foreign key (customer_id) references customers(id),
    constraint fk_review_project foreign key (project_id) references project(id)
);

-- REVIEW_IMAGES
create table review_images (
    review_id bigint not null,
    image_url varchar(255) not null,
    constraint pk_review_images primary key(review_id, image_url),
    constraint fk_review_images_review foreign key (review_id) references review(id)
);

-- REFRESH TOKENS
create table refresh_tokens (
    id bigint generated by default as identity primary key,
    token varchar(500) not null unique,
    expiry_date timestamp with time zone not null,
    revoked boolean not null default false,
    user_id bigint not null,
    constraint fk_refresh_user foreign key (user_id) references users(id)
);

-- SETUP TOKENS (NEW)
create table setup_tokens (
    id bigint generated by default as identity primary key,
    token varchar(255) not null unique,
    user_id bigint not null unique,
    expiration timestamp with time zone not null,
    used boolean not null default false,
    constraint fk_setup_token_user
        foreign key (user_id) references users(id)
        on delete cascade
);